### ISSUE TITLE
Move GoAheui to aheui organization

### ISSUE THREAD

**Issue by sungwoncho** [aheui/aheui.github.io#22]
I implemented Aheui in Go: https://github.com/sungwoncho/goaheui.

Moving the repo to this organization will allow better collaboration. Any thoughts?

**Comment by youknowone** [comment]
As I remember, you can transfer your repository to any org without permission. When you transferred your repository, admins will give you access permission of GoAheui. (Tell me if the policy of github is changed)

It is not a requirement, but you can add spec test and CI from /snippets.
- Makefile in caheui is here: https://github.com/aheui/caheui/blob/master/Makefile
- travis setup file is here: https://github.com/aheui/caheui/blob/master/.travis.yml

**Comment by sungwoncho** [comment]
I think GitHub policy has changed.

Transfer repository in repository settings tab says:

> Transfer this repository to another user or to an organization where you have the ability to create repositories.

When I attempt to transfer the repo anyway, I get that I have no permission to create repos in aheui organization.

As for the CI, I will gradually write some tests and set up Travis.

**Comment by puzzlet** [comment]
added @sungwoncho as a member.

**Comment by sungwoncho** [comment]
Thank you @puzzlet. Closing this issue.
